project_id = "rwtdgknbahnvjkydzjzp"

[functions.send-email-confirmation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-document-email]
verify_jwt = true
